/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    `java-library`
    `maven-publish`
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://raw.github.com/JRakNet/WaifUPnP/master/")
    }

    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }
}

dependencies {
    api("org.apache.logging.log4j:log4j-api:2.17.1")
    api("org.apache.logging.log4j:log4j-core:2.17.1")
    api("io.netty:netty-handler:4.1.49.Final")
    api("com.dosse:upnp:1.1")
}

group = "com.whirvis"
version = "2.12.4-SNAPSHOT"
description = "JRakNet"
java.sourceCompatibility = JavaVersion.VERSION_1_8

java {
    withSourcesJar()
    withJavadocJar()
}

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}

tasks.withType<JavaCompile>() {
    options.encoding = "UTF-8"
}

tasks.withType<Javadoc>() {
    options.encoding = "UTF-8"
}
